{% set version = "3.5.7" %}

package:
  name: rsgislib
  version: {{ version }}

source:
  url: https://bitbucket.org/petebunting/rsgislib/downloads/rsgislib-{{ version }}.tar.gz
  sha256: 546c9c930faee49976c93bf42be927c57be053795585c8746bb824ae58206a5b
  patches:
    # boost libs have changed their names recently
    - winboost.patch  # [win]

build:
  number: 1
  # CGAL etc do not support earlier than vc14
  skip: True  # [win and py<35]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - cmake
    - toolchain
    - hdf5 1.10.1|1.10.1.*
    - xerces-c 3.2.0
    - muparser
    - gsl 2.2.*
    - geos 3.6.2
    - gdal 2.2.*
    - boost-cpp 1.66.0
    - kealib
    # cgal pulls in appropriate mpir/mpfr/gmp etc for platform
    - cgal
    - python
    - vc   9  # [win and py27]
    - vc  14  # [win and (py35 or py36)]
    - libstdcxx-ng  # [linux]

  run:
    - hdf5 1.10.1|1.10.1.*
    - xerces-c 3.2.0
    - muparser
    - gsl 2.2.*
    - geos 3.6.2
    - gdal 2.2.*
    - boost-cpp 1.66.0
    - kealib
    # cgal pulls in appropriate mpir/mpfr/gmp etc for platform
    - cgal
    - python
    - vc   9  # [win and py27]
    - vc  14  # [win and (py35 or py36)]
    - libstdcxx-ng  # [linux]

test:
  source_files:
    - python_tests
  commands:
    - cd python_tests/RSGISLibTests && python RSGIStests.py --all
    # These are timming out :-(
    # - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    # - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
  imports:
    - rsgislib
    - rsgislib.imagecalibration
    - rsgislib.classification
    - rsgislib.elevation
    - rsgislib.imagecalc
    - rsgislib.imagefilter
    - rsgislib.imageregistration
    - rsgislib.imageutils
    - rsgislib.rastergis
    - rsgislib.segmentation
    - rsgislib.vectorutils
    - rsgislib.zonalstats
    # get a memory error here - must investigate
    #- rsgislib.histocube
    - rsgislib.imagemorphology

about:
  home: http://www.rsgislib.org
  license: GPL3
  license_file: LICENSE.txt
  summary: The Remote Sensing and GIS software library (RSGISLib) is a collection of Python modules for processing remote sensing and GIS datasets.

extra:
  recipe-maintainers:
    - danclewley
    - petebunting
    - gillins
