travis:
  secure:
    BINSTAR_TOKEN: t9zHSz7WsgqLaIaJhzmMUaPvmVroxxbOSygXGj6XYTP6wrgfi16+2TyHA0rjY2yGLNdf660EUkAKWK0Qjnpc6ocIl3zwX2PtdTSwDpomsuUfmIaMFUSOeapLqg7gnsdCVQdO2tJ8SFkiE4evaez0tXHVShxZ62g+qL3aOE5TK76VE8wWWuHTPdMMuxY8QEHWQdWhTWAfqqwjI25mNBWFq8fgZPgUs20cd4FSMaqyKme3OwaiMw3sHwag3TgDICupHz0ptlBn2JR07l7xg+C3yErwsLadksrtR9m+8QLVdZca8MKs8RKjexJYCRjdoLe01cJ20/W1NEi/tGtHMmpS9f8z1S7db1+hQKyRFRQyiwMAbRKZEv6UkeK+6gWZwIVydgGJ00EFXcmWQv0dl9r5PIwy5EkbFOGEYykv25sYSkHbnPH8QHDqMgjUIPEOx4AluKZmzsjdZEOrakaZbebNgUA1L9C38az8UdINGK236M9cuomowZAGl/y6ckQrZb8cpNqJIsoNlKJW6l7N4LZPZdR6akV5pQtK98AyCOS5NBkt5d9/d3lQ6QpflQnsROS2fkUGqAzLEHH0+te70P3NqGa0oaPca5erwXGgsNCkaFKWaLayCsxlHpaPgiCae0qUJ2uAiZmyl8ntV306tHFlIRMAbsK0Zcm4ldmU4z7ZMkI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
